### ISSUE TITLE
 The specified module could not be found

### ISSUE THREAD

**Issue by Winner244** [reklatsmasters/node-process-list#29]
cmd: 
"cd .../node_modules/process-list"
"node example.js" 
Error:
The specified module could not be found.
\\?\D:\....\node_modules\process-list\build\Release\processlist.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (D:\...\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (D:\...\node_modules\process-list\index.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)

**Comment by fraxken** [comment]
Hi,

Have you installed npm packages with the command `npm install` ?

If yes, have you encountered problems during the installation ? Maybe a problem with node-gyp compilation ?

Take a look at: https://www.npmjs.com/package/windows-build-tools

Best Regards,
Thomas
