### ISSUE TITLE
install error at mac

### ISSUE THREAD

**Issue by atian25** [reklatsmasters/node-process-list#6]
```bash
➜  tmp npm i process-list

> process-list@1.2.1 install /Users/tz/Workspaces/tmp/node_modules/process-list
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.1
prebuild-install info looking for local prebuild @ prebuilds/process-list-v1.2.1-node-v57-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/tz/.npm/_prebuilds/https-github.com-reklatsmasters-node-process-list-releases-download-v1.2.1-process-list-v1.2.1-node-v57-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/reklatsmasters/node-process-list/releases/download/v1.2.1/process-list-v1.2.1-node-v57-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/reklatsmasters/node-process-list/releases/download/v1.2.1/process-list-v1.2.1-node-v57-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.1.4 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/processlist/src/main.o
  CXX(target) Release/obj.target/processlist/src/snapshot.o
../src/snapshot.cpp:41:5: error: cannot use 'try' with exceptions disabled
    try {
    ^
1 error generated.
make: *** [Release/obj.target/processlist/src/snapshot.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tz/git/nvs/node/8.1.4/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/tz/git/nvs/node/8.1.4/x64/bin/node" "/Users/tz/git/nvs/node/8.1.4/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tz/Workspaces/tmp/node_modules/process-list
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/tz/Workspaces/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! process-list@1.2.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the process-list@1.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tz/.npm/_logs/2017-08-02T01_50_28_790Z-debug.log
```

**Comment by reklatsmasters** [comment]
Sorry, i haven't MacBook to add support OSX. See #2.

**Comment by atian25** [comment]
thanks all the same

**Comment by ghost** [comment]
It doesn't install on windows either
